Add delete queue endpoints
Notifiarr/notifiarr pull request #663
Opened 2024-02-08 04:03 UTC by davidnewhall

Adds endpoints to delete things from the queue.

- Check spelling and wrong starr app etc.
- Default delete options?

2024-02-08 17:57 UTC, bakerboy448 requested changes
given:
- RemoveFromClient: false
- BlockList: false
- SkipRedownload: false
- ChangeCategory: True

Outcome: change categories; don't search for a new release; don't add to blocklist; keep in client

2024-02-08 17:57 UTC, bakerboy448 commented on pkg/apps/lidarr.go
> +		BlockList:        true,
should not default to blocklist the entry

2024-02-08 17:57 UTC, bakerboy448 commented on pkg/apps/radarr.go
> +		BlockList:        true,
don't default to blocklisting

2024-02-08 17:57 UTC, bakerboy448 commented on pkg/apps/readarr.go
> +		BlockList:        true,
don't default to blocklisting

2024-02-08 17:57 UTC, bakerboy448 commented on pkg/apps/sonarr.go
> +		BlockList:        true,
don't default to blocklisting

2024-02-08 19:17 UTC, davidnewhall commented
at the point of having a queue ID I do not know if it's usenet or torrent. I can add an input for the php to make the decision. Need input from @austinwbest

2024-02-08 20:35 UTC, austinwbest commented
I honestly dont care what the default is as i'll always send it populated based on the request

2024-02-09 17:29 UTC, davidnewhall commented
So you need to change things? What do you need to change? I need details.

2024-04-07 00:48 UTC, austinwbest commented
> So you need to change things? What do you need to change? I need details.

You have support for all 4 parameters in starr, add support for all 4 parameters in the client

2024-04-07 01:36 UTC, davidnewhall commented
All four queue delete options are exposed as GET parameters. They all default to `false`.

2024-04-07 01:47 UTC, austinwbest commented
Add the parameters to the API docs for this endpoint

2024-04-07 18:42 UTC, merged